# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command, without env
#   $ conda activate hzsite
#
name: bp_mlbmat
channels:
  - conda-forge
dependencies:
  # numpy distutils is needed for qml in the kernel methods tutorial
  # So no 3.12 either
  - numpy<=1.22
  - python
  - jupyter
  - jupytext
  - tqdm
  - pip
  - pip:
    - git+https://github.com/qmlcode/qml.git@a7921c9
